name: Post Preview-URL

on: pull_request

jobs:
  quote-job-image:
    name: Build Quote Image
    runs-on: ubuntu-latest
    outputs:
      STORED_QUOTE_IMAGE_TAG: ${{ steps.tag.outputs.STORED_QUOTE_IMAGE_TAG }}
    env:
      DEV_REGISTRY: ${{ secrets.DEV_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout local
        uses: actions/checkout@v3
        with:
          path: local

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"

      - name: "Docker Login"
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Quote
        id: tag
        env:
          GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
        run: |
          
          # export pull number
          cd local
          export PULL_NUM=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          export COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")

          docker build -t $DEV_REGISTRY:$PULL_NUM-COMMIT_HASH ./local
          echo "STORED_QUOTE_IMAGE_TAG=$DEV_REGISTRY:$PULL_NUM-COMMIT_HASH" >> $GITHUB_ENV

      - name: Push Quote Image
        run: |
          docker push $STORED_QUOTE_IMAGE_TAG

      - name: Store Quote Image Tag
        id: tag
        run: |
          TAG=${STORED_QUOTE_IMAGE_TAG}
          echo "marking STORED_QUOTE_IMAGE_TAG as ${TAG}"
          echo "::set-output name=STORED_QUOTE_IMAGE_TAG::${TAG}"

  comment:
    name: Deploy Preview Manifests # Posts a comment on PR open for testing
    runs-on: ubuntu-latest
    needs:
      - quote-job-image
    env:
      STORED_QUOTE_IMAGE_TAG: ${{ needs.quote-job-image.outputs.STORED_QUOTE_IMAGE_TAG }}
    steps:
      - name: Checkout local
        uses: actions/checkout@v3
        with:
          path: local

      - name: Checkout remote
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          repository: AliceProxy/deploy-preview
          path: remote

      - name: push manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |

          # export pull number
          cd local
          export PULL_NUM=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          export COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")

          # copy the manifest to the remote directory
          cd ../remote
          cp ./manifests/quote-deploy.yaml ./manifests/quote-deploy-preview-PR$PULL_NUM.yaml

          manifest=./manifests/quote-deploy-preview-PR$PULL_NUM.yaml

          name=$(yq '.metadata.name' $manifest)
          namespace=$(yq '.metadata.namespace' $manifest)

          # set/modify the app label and remove all others
          yq -i '.spec.template.metadata.labels.app = '\"${name}'-deploy-preview-PR'${PULL_NUM}\" $manifest
          yq -i '.spec.template.metadata |= .labels |= with_entries(select(.key == "app"))' $manifest

          # Again for the selector
          yq -i '.spec.selector.matchLabels.app = '\"${name}'-deploy-preview-PR'${PULL_NUM}\" $manifest
          yq -i '.spec.selector |= .matchLabels |= with_entries(select(.key == "app"))' $manifest

          # update the image. Right now this edits every container in the deployment. 
          # TODO: edit this to only be for a specific container incase there are multiple containers
          yq -i '.spec.template.spec.containers[] |= .image = '\"${STORED_QUOTE_IMAGE_TAG}\" $manifest

          yq -i '.metadata.name = '\"${name}'-deploy-preview-PR'${PULL_NUM}\" $manifest
          yq -i '.metadata.namespace = "deploy-previews"' $manifest

          git config --unset-all http.https://github.com/.extraheader # this is required to unset all the config from the current repository (the one running this job)

          git config user.name "AliceProxy"
          git config user.email "alicewasko@datawire.io"

          # TODO: If CI fails in the middle of a run or for whatever reason the deployment preview manifest already exists in the remote repo this will fail since there are no differences
          git add $manifest
          git commit -m "create preview deployment"

          #git push --set-upstream deploy-preview-$PULL_NUM
          git push https://$GITOPS_TOKEN@github.com/AliceProxy/deploy-preview.git

      - name: Comment complete
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.issue.owner,
              repo: context.repo.repo,
              body: 'Your preview manifests have been pushed to the gitops repository'
            })
